# Convolutional Neural Networks (cats and dogs dataset)

In [1]:
# importing all the libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
import matplotlib.pyplot as plt

In [2]:
from sklearn.metrics import accuracy_score,confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Conv2D,Dense,MaxPool2D
from tensorflow.keras.utils import to_categorical
import os
import cv2

In [3]:
# loading dataset
path1 = r'D:\Datasets\catsdogs'
cate = ['cats','dogs']

In [4]:
for i in cate:
    folders = os.path.join(path1,i)
    print(folders)

D:\Datasets\catsdogs\cats
D:\Datasets\catsdogs\dogs


In [27]:
#setting image dimensions
image_size = 200


In [28]:
# storing all the images in array format in input_image 
input_image = []
for i in cate:
    folders = os.path.join(path1,i)
    label = cate.index(i)
    print("Value of label is: ",label)
    for image in os.listdir(folders):
        image_path = os.path.join(folders,image)
        if image_path == 'D:\Datasets\catsdogs\dogs\desktop.ini':
            continue
        image_array = cv2.imread(image_path)
        image_array = cv2.resize(image_array, (image_size,image_size)) 
        input_image.append( [image_array,label] )

Value of label is:  0
Value of label is:  1


In [9]:
len(input_image)

3998

In [10]:
#shuffling the array
np.random.shuffle(input_image)

In [11]:
# till here x and y values are together. We need to separate them
X = []
Y = []

for x_values,labels in input_image:
    X.append(x_values)
    Y.append(labels)

In [12]:
X = np.array(X)
Y = np.array(Y)

In [13]:
X.shape

(3998, 200, 200, 3)

In [14]:
Y.shape

(3998,)

In [15]:
Y
X = X / 255

In [16]:
# creating the model 
model = Sequential()

In [17]:
# adding input,hidden and output layers
model.add(Conv2D(filters = 20,kernel_size = (10,10),input_shape = (200,200,3) ,activation = 'relu',padding = 'same'))
model.add(MaxPool2D(pool_size = (5,5)))
model.add(Flatten())

model.add(Dense(128,activation = 'relu'))
model.add(Dense(2,activation = 'softmax'))

In [18]:
# compiling the model with opyimizer 'adam'
model.compile(optimizer = 'adam',loss = 'sparse_categorical_crossentropy',metrics = ['accuracy'])

In [19]:
# fitting the model 
model.fit(X,Y,epochs = 10,batch_size = 64,validation_split = 0.2)

Epoch 1/10
50/50 [==============================] - 83s 2s/step - loss: 1.0453 - accuracy: 0.5672 - val_loss: 0.6816 - val_accuracy: 0.5838
Epoch 2/10
50/50 [==============================] - 78s 2s/step - loss: 0.6815 - accuracy: 0.5700 - val_loss: 0.6769 - val_accuracy: 0.5863
Epoch 3/10
50/50 [==============================] - 77s 2s/step - loss: 0.6682 - accuracy: 0.5913 - val_loss: 0.6724 - val_accuracy: 0.5863
Epoch 4/10
50/50 [==============================] - 76s 2s/step - loss: 0.6273 - accuracy: 0.6329 - val_loss: 0.6652 - val_accuracy: 0.6012
Epoch 5/10
50/50 [==============================] - 77s 2s/step - loss: 0.5748 - accuracy: 0.6826 - val_loss: 0.6494 - val_accuracy: 0.6350
Epoch 6/10
50/50 [==============================] - 80s 2s/step - loss: 0.4967 - accuracy: 0.7583 - val_loss: 0.6931 - val_accuracy: 0.6400
Epoch 7/10
50/50 [==============================] - 77s 2s/step - loss: 0.4061 - accuracy: 0.8180 - val_loss: 0.7412 - val_accuracy: 0.6450
Epoch 8/10
50/50 [==

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 200, 200, 20)      6020      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 40, 40, 20)       0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 32000)             0         
                                                                 
 dense (Dense)               (None, 128)               4096128   
                                                                 
 dense_1 (Dense)             (None, 2)                 258       
                                                                 
Total params: 4,102,406
Trainable params: 4,102,406
Non-trainable params: 0
______________________________________________

In [21]:
#calculating prediciton accuracy
pred = model.predict(X)

125/125 [==============================] - 13s 92ms/step


In [22]:
pred

array([[0.45447737, 0.5455227 ],
       [0.4184496 , 0.5815504 ],
       [0.47571772, 0.5242823 ],
       ...,
       [0.01952315, 0.98047686],
       [0.70850825, 0.29149175],
       [0.11835644, 0.8816436 ]], dtype=float32)

In [23]:
pred_classes = np.argmax(pred,axis = 1)

In [24]:
pred_classes

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [25]:
catdog_cf = confusion_matrix(Y,pred_classes)
catdog_cf

array([[1523,  187],
       [ 238, 2050]], dtype=int64)

In [26]:
accuracy_score(Y,pred_classes)*100

89.36968484242122