In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns' , None)
pd.set_option('display.max_rows' , None)

In [3]:
bk = pd.read_csv(r'bank_data.csv')

In [4]:
bk.head(15)

ID  Gender  Age Region_Code     Occupation Channel_Code  Vintage  \
0   NNVBBKZB  Female   73       RG268          Other           X3       43   
1   IDD62UNG  Female   30       RG277       Salaried           X1       32   
2   HD3DSEMC  Female   56       RG268  Self_Employed           X3       26   
3   BF3NC7KV    Male   34       RG270       Salaried           X1       19   
4   TEASRWXV  Female   30       RG282       Salaried           X1       33   
5   ACUTYTWS    Male   56       RG261  Self_Employed           X1       32   
6   ETQCZFEJ    Male   62       RG282          Other           X3       20   
7   JJNJUQMQ  Female   48       RG265  Self_Employed           X3       13   
8   ZMQFYKCB  Female   40       RG283  Self_Employed           X2       38   
9   NVKTFBA2  Female   55       RG268  Self_Employed           X2       49   
10  NVC424KZ    Male   53       RG254  Self_Employed           X3      123   
11  GZ5TMYIR    Male   27       RG270  Self_Employed           X1       14   
12  FCPEEIY3  Female   27       RG277       Salaried           X1       20   
13  KCE7JSFN    Male   31       RG254       Salaried           X1       31   
14  EMEEHHBK    Male   79       RG277          Other           X3       57   

   Credit_Product  Avg_Account_Balance Is_Active  Is_Lead  
0              No              1045696        No        0  
1              No               581988        No        0  
2              No              1484315       Yes        0  
3              No               470454        No        0  
4              No               886787        No        0  
5              No               544163       Yes        0  
6             NaN              1056750       Yes        1  
7              No               444724       Yes        0  
8              No              1274284        No        0  
9             Yes              2014239        No        0  
10             No               980664       Yes        0  
11            Yes               502787        No        0  
12             No               811591       Yes        0  
13            Yes               938754        No        0  
14             No               832185       Yes        0

In [5]:
bk.shape

(245725, 11)

In [6]:
bk.Region_Code.value_counts()

RG268    35934
RG283    29416
RG254    26840
RG284    19320
RG277    12826
RG280    12775
RG269     7863
RG270     7720
RG261     7633
RG257     6101
RG251     5950
RG282     5829
RG274     5286
RG272     5252
RG281     5093
RG273     4497
RG252     4286
RG279     3976
RG263     3687
RG275     3245
RG260     3110
RG256     2847
RG264     2793
RG276     2764
RG259     2586
RG250     2496
RG255     2018
RG258     1951
RG253     1858
RG278     1822
RG262     1788
RG266     1578
RG265     1546
RG271     1542
RG267     1497
Name: Region_Code, dtype: int64

In [7]:
bk.isnull().sum()

ID                         0
Gender                     0
Age                        0
Region_Code                0
Occupation                 0
Channel_Code               0
Vintage                    0
Credit_Product         29325
Avg_Account_Balance        0
Is_Active                  0
Is_Lead                    0
dtype: int64

In [8]:
bk.Credit_Product.value_counts()

No     144357
Yes     72043
Name: Credit_Product, dtype: int64

In [9]:
bk = bk.drop(['ID'], axis=1)

In [10]:
bk.shape

(245725, 10)

In [11]:
bk.Credit_Product=bk.Credit_Product.fillna('No')

In [12]:
bk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245725 entries, 0 to 245724
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   Gender               245725 non-null  object
 1   Age                  245725 non-null  int64 
 2   Region_Code          245725 non-null  object
 3   Occupation           245725 non-null  object
 4   Channel_Code         245725 non-null  object
 5   Vintage              245725 non-null  int64 
 6   Credit_Product       245725 non-null  object
 7   Avg_Account_Balance  245725 non-null  int64 
 8   Is_Active            245725 non-null  object
 9   Is_Lead              245725 non-null  int64 
dtypes: int64(4), object(6)
memory usage: 18.7+ MB


In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
bk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245725 entries, 0 to 245724
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   Gender               245725 non-null  object
 1   Age                  245725 non-null  int64 
 2   Region_Code          245725 non-null  object
 3   Occupation           245725 non-null  object
 4   Channel_Code         245725 non-null  object
 5   Vintage              245725 non-null  int64 
 6   Credit_Product       245725 non-null  object
 7   Avg_Account_Balance  245725 non-null  int64 
 8   Is_Active            245725 non-null  object
 9   Is_Lead              245725 non-null  int64 
dtypes: int64(4), object(6)
memory usage: 18.7+ MB


In [15]:
le = LabelEncoder()

In [16]:
bk[bk.select_dtypes(include=['object']).columns] = bk[bk.select_dtypes(include=['object']).columns].apply(le.fit_transform)

In [17]:
bk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245725 entries, 0 to 245724
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Gender               245725 non-null  int32
 1   Age                  245725 non-null  int64
 2   Region_Code          245725 non-null  int32
 3   Occupation           245725 non-null  int32
 4   Channel_Code         245725 non-null  int32
 5   Vintage              245725 non-null  int64
 6   Credit_Product       245725 non-null  int32
 7   Avg_Account_Balance  245725 non-null  int64
 8   Is_Active            245725 non-null  int32
 9   Is_Lead              245725 non-null  int64
dtypes: int32(6), int64(4)
memory usage: 13.1 MB


In [18]:
bk.head()

Gender  Age  Region_Code  Occupation  Channel_Code  Vintage  \
0       0   73           18           1             2       43   
1       0   30           27           2             0       32   
2       0   56           18           3             2       26   
3       1   34           20           2             0       19   
4       0   30           32           2             0       33   

   Credit_Product  Avg_Account_Balance  Is_Active  Is_Lead  
0               0              1045696          0        0  
1               0               581988          0        0  
2               0              1484315          1        0  
3               0               470454          0        0  
4               0               886787          0        0

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
bk_train , bk_test = train_test_split(bk, test_size = .2)

In [21]:
bk_train_x = bk_train.iloc[: , 0:-1]
bk_train_y = bk_train.iloc[: , -1]

In [22]:
bk_test_x = bk_test.iloc[: , 0:-1]
bk_test_y = bk_test.iloc[: , -1]

In [23]:
bk_train_x.shape

(196580, 9)

In [24]:
from sklearn.tree import DecisionTreeClassifier
dec_tree = DecisionTreeClassifier(criterion="gini",max_depth=10,class_weight='balanced')

In [25]:
dec_tree.fit(bk_train_x, bk_train_y)

DecisionTreeClassifier(class_weight='balanced', max_depth=10)

In [26]:
pred_dec = dec_tree.predict(bk_test_x)
pred_dec

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
dec_bk = confusion_matrix(bk_test_y , pred_dec)
dec_bk

array([[26128, 11400],
       [ 3119,  8498]], dtype=int64)

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy_score(bk_test_y , pred_dec)*100

70.45681147624376

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
log_bk = LogisticRegression()

In [30]:
log_bk.fit(bk_train_x, bk_train_y);  

In [31]:
pred = log_bk.predict(bk_test_x)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
len(pred)

49145

In [34]:
tab_bk = confusion_matrix(bk_test_y , pred)
tab_bk

array([[37466,     0],
       [11679,     0]], dtype=int64)

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracy_score(bk_test_y , pred)*100

76.23562926035203